version: '3.4'

services:
  dmr:
    build:
      context: ../DMR/src/Dmr.Api
      dockerfile: Dockerfile
    ports:
      - "9010:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DMRSERVICESETTINGS__CLASSIFIERURI=http://classifier/dmr-api/messages
      - DMRSERVICESETTINGS__CENTOPSURI=http://centops
      - DMRSERVICESETTINGS__CENTOPSAPIKEY=testingadmin
    networks:
      - my-network

  classifier:
    build:
      context: ../Mock-Classifier/src/MockClassifier.Api
      dockerfile: Dockerfile
    ports:
      - "9011:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DMRSERVICESETTINGS__DMRAPIURI=http://dmr/messages
    networks:
      - my-network

  bot1:
    build:
      context: ../Mock-Bot/src/MockBot.Api
      dockerfile: Dockerfile
    ports:
      - "9012:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DMRSERVICESETTINGS__DMRAPIURI=http://dmr/messages
      - BOTSETTINGS__ID=bot1
    networks:
      - my-network

  bot2:
    build:
      context: ../Mock-Bot/src/MockBot.Api
      dockerfile: Dockerfile
    ports:
      - "9013:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DMRSERVICESETTINGS__DMRAPIURI=http://dmr/messages
      - BOTSETTINGS__ID=bot2
    networks:
      - my-network

  centops:
    build:
      context: ../CentOps/src
      dockerfile: ./CentOps.Api/Dockerfile
    ports:
      - "9014:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - my-network

networks:
  my-network:
    external: true